### ISSUE TITLE
Error: Cannot find module 'gulp-ruby-sass'

### ISSUE THREAD

**Issue by shanecarmody** [zurb/foundation-apps#214]
I successfully installed `foundation-apps` on my machine but I’m having trouble when it comes to the `npm start` command. Here is the output when I run `npm start` (I get the same error when I run `foundation-apps watch`:

``` sh
shanecarmody@MBP ~/Sites/test: npm start

> foundation-apps-template@0.0.1 start /Users/shanecarmody/Sites/test
> gulp

Error: Cannot find module 'gulp-ruby-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/shanecarmody/Sites/test/gulpfile.js:6:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! foundation-apps-template@0.0.1 start: `gulp`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the foundation-apps-template@0.0.1 start script.
npm ERR! This is most likely a problem with the foundation-apps-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-apps-template
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/shanecarmody/Sites/test
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/shanecarmody/Sites/test/npm-debug.log
npm ERR! not ok code 0 
```

I’m reporting this here as the output says:

> This is most likely a problem with the foundation-apps-template package not with npm itself

Thanks!

**Comment by Edward-Shaw** [comment]
" Whenever you see a "Cannot find module" error, it means you're missing an npm package, so you can run npm install to get the package."
