### ISSUE TITLE
CLI 1.1 does not download file in gulp-sass

### ISSUE THREAD

**Issue by Joe-5mith** [zurb/foundation-apps#541]
I updated CLI to 1.1 with the following in Terminal: `npm update -g foundation-cli`.

I then ran: `foundation-apps new my_project`.

I got the following error after "Installing dependencies..." appeared in Terminal:

```
> node-sass@2.0.1 install /.../my_project/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-ia32-node-0.12/binding.node

> node-sass@2.0.1 postinstall /.../my_project/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/.../my_project/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Build failed
```

npm version 2.5.1.

I can't work on my Foundation for Apps projects because of this.

**Comment by gakimball** [comment]
Looks like some weird network issue. Can you try running everything manually? `cd` into the folder for the project that was created and run:

```bash
npm install
bower install
gulp
```

**Comment by Joe-5mith** [comment]
After running those commands in the project folder, I get:

```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/.../my_project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/.../my_project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/.../my_project/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:460:26)
Error running task sequence: { task: 'sass',
  message: 'sass catch',
  duration: 0.012710486,
  hrDuration: [ 0, 12710486 ],
  err: [Error: `libsass` bindings not found. Try reinstalling `node-sass`?] }

```

**Comment by gakimball** [comment]
Did you get any errors when you ran `npm install`?

**Comment by Joe-5mith** [comment]
No errors on `npm install` or on `bower install`.

**Comment by gakimball** [comment]
Hmm, well you got an error the first time, so let's try again.

```bash
rm -rf node_modules
npm cache clean
npm install
```

See if you get the same errors with node-sass. Also, what version of Node are you running?

If this doesn't work, you'll likely need to ask the folks at [node-sass](https://github.com/sass/node-sass/issues) for some help.

**Comment by Joe-5mith** [comment]
It seems from some node-sass forum posts that node-sass perhaps does not support older operating systems.

How can I compile with Ruby instead of libsass?

After running the commands suggested, I got the same error as I listed in the original post of this issue.

My node version is: 0.12.0.

**Comment by gakimball** [comment]
Swapping for Ruby Sass is fairly easy. Install the `gulp-ruby-sass` library and then replace the code in the `sass` task of your Gulpfile with this code:

```js
return gulp.src('client/assets/scss/app.scss')
  .pipe($.rubySass({
    loadPath: paths.sass,
    style: 'nested'
  })).on('error', function (e) {
    console.log(e);
  })
  .pipe($.autoprefixer({
    browsers: ['last 2 versions', 'ie 10']
  }))
  .pipe(gulp.dest('./build/assets/css/'));
```

**Comment by Joe-5mith** [comment]
When I use `foundation-apps watch` in Terminal, I get the following error:

```
[17:06:35] Starting 'sass'...
[17:06:35] 'sass' errored after 51 ms
[17:06:35] TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at Object.module.exports (/.../my_project/node_modules/gulp-ruby-sass/index.js:65:15)
    at Gulp.<anonymous> (/.../my_project/gulpfile.js:66:13)
    at module.exports (/.../my_project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/.../my_project/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/.../my_project/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /.../my_project/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/.../my_project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/.../my_project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at Gulp.<anonymous> (/.../my_project/gulpfile.js:133:3)
Error running task sequence: { task: 'sass',
  message: 'sass catch',
  duration: 0.050536951,
  hrDuration: [ 0, 50536951 ],
  err: [TypeError: Arguments to path.join must be strings] }
Successfully built.

```

I used `npm install gulp-ruby-sass`.

**Comment by Joe-5mith** [comment]
New syntax was introduced for gulp-ruby-sass 1.x. This looks like it might be working:

```
gulp.task('sass', function() {
    return $.rubySass('client/assets/scss/app.scss', {
    		loadPath: paths.sass,
    		style: 'nested'
    	})
    	.pipe($.autoprefixer({
   			 browsers: ['last 2 versions', 'ie 10']
 		}))
        .pipe(gulp.dest('./build/assets/css/'));
});
```

**Comment by gakimball** [comment]
Right! Forgot they have a new 1.0 alpha branch. One more thing, if you want to lock in the version of Sass you're using with a Gemfile, you can add one to the project root, run `bundle install`, and then add the setting `bundleExec: true` to the `$.rubySass` config object.

**Comment by gakimball** [comment]
@Joe-5mith Were you able to get gulp-ruby-sass working properly?

**Comment by Joe-5mith** [comment]
Excuse me for the delay. Yes, the above steps work. Thank you for your rapid responses.

For those who use haven't used the older version of Foundation for Apps, here are the two Gemfiles that I placed in the root folder of my  Foundation for apps project and the final gulpfile.js code:

The `Gemfile.lock` file:
```
GEM
  remote: https://rubygems.org/
  specs:
    sass (3.4.9)

PLATFORMS
  ruby

DEPENDENCIES
  sass (~> 3.4.0)
```

The `Gemfile` file:
```
source "https://rubygems.org"

gem "sass", "~> 3.4.0"

```

The final code in `gulpfile.js` was:

```
gulp.task('sass', function() {
    return $.rubySass('client/assets/scss/app.scss', {
    		loadPath: paths.sass,
    		style: 'nested',
    		bundleExec: true
    	})
    	.pipe($.autoprefixer({
   			 browsers: ['last 2 versions', 'ie 10']
 		}))
        .pipe(gulp.dest('./build/assets/css/'));
});
```
