### ISSUE TITLE
Error while setting up a new Project

### ISSUE THREAD

**Issue by NicoBleh** [zurb/foundation-apps#554]
Following the docs i typed
```
foundation-apps new myApp
```
which leads to
```
gulp-sass@1.3.3 node_modules/gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── node-sass@2.0.1 (object-assign@2.0.0, get-stdin@4.0.1, replace-ext@0.0.1, cross-spawn@0.2.6, nan@1.7.0, mkdirp@0.5.0, chalk@0.5.1, semver@4.3.2, shelljs@0.3.0, meow@3.1.0, npmconf@2.1.1, gaze@0.5.1, request@2.54.0, mocha@2.2.1, sass-graph@1.2.0)
/usr/local/lib/node_modules/bower/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Failed to execute "git ls-remote --tags --heads git://github.com/HubSpot/tether.git", exit code of #128
    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/bower/lib/util/cmd.js:102:21)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by NicoBleh** [comment]
That works!

I'm trying to reproduce on a different machine.

**Comment by gakimball** [comment]
Hmm, could have been a temporary network hiccup or an issue with proxies, depending on the kind of network you're on. If it happens again let us know. :)
