### ISSUE TITLE
Foundation-Apps new is throwing ENOENT erro

### ISSUE THREAD

**Issue by mearleycf** [zurb/foundation-apps#620]
This is the error I'm getting when I run 

`foundation-apps new mwepd2`

<pre>Downloading the Foundation for Apps template.../usr/local/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^
Error: ENOENT, no such file or directory
    at Error (native)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:14:9)
    at /usr/local/lib/node_modules/foundation-cli/lib/commands/new.js:62:13
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/exec/exec.js:90:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)</pre>

**Comment by gakimball** [comment]
The Git clone may have failed. Can you try running the command manually?

```
git clone https://github.com/zurb/foundation-apps-template.git mwepd2
```

**Comment by mearleycf** [comment]
I was able to clone it manually, but once I clone it manually, and run npm install, bower install, and bundle, it's failing on bundle--no gemfile.

**Comment by gakimball** [comment]
Oh! You're on an old version of the CLI—it doesn't use Ruby at all now. Run `npm update -g foundation-cli`.

**Comment by soulstyle** [comment]
Im still experiencing this issue after updating foundation-cli.

```
Downloading the Foundation for Apps template.../usr/local/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^
Error: ENOENT, no such file or directory
    at Error (native)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/npm-registry-client/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/write-file-atomic/node_modules/graceful-fs/polyfills.js:14:9)
    at /usr/local/lib/node_modules/foundation-cli/lib/commands/new.js:63:13
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/exec/exec.js:90:5)
    at ChildProcess.emit (events.js:110:17)
```

**Comment by gakimball** [comment]
@soulstyle Do you see a project folder being created after running `foundation-apps new`? The folder should still be there even if the install fails.
