### ISSUE TITLE
foundation-apps doesnt work and manual method produces hung process

### ISSUE THREAD

**Issue by dredgerman** [zurb/foundation-apps#721]
Installed myApp using manual method described in gitIssue, when npm start used (after uninstalling bundler and reinstalling) process just hangs indefinitely,

[tom@server ~]$ cd myApp
[tom@server myApp]$ npm start

> foundation-apps-template@1.1.0 start /home/tom/myApp
> gulp

[10:41:34] Using gulpfile ~/myApp/gulpfile.js
[10:41:34] Starting 'build'...
[10:41:34] Starting 'clean'...
[10:41:34] Finished 'clean' after 13 ms
[10:41:34] Starting 'copy'...
[10:41:34] Starting 'copy:foundation'...
[10:41:34] Finished 'copy:foundation' after 211 ms
[10:41:34] Starting 'sass'...
[10:41:35] Starting 'uglify:foundation'...
[10:41:35] Starting 'uglify:app'...
[10:41:35] Finished 'copy' after 940 ms
[10:41:35] Finished 'uglify:app' after 237 ms
[10:41:35] Finished 'uglify:foundation' after 632 ms
[10:41:35] Starting 'uglify'...
[10:41:35] Finished 'uglify' after 19 μs
[10:41:36] Finished 'sass' after 1.47 s
[10:41:36] Starting 'copy:templates'...
[10:41:36] Finished 'copy:templates' after 17 ms
[10:41:36] Finished 'build' after 1.73 s
[10:41:36] Starting 'server'...
[10:41:36] Webserver started at http://localhost:8079
[10:41:36] Finished 'server' after 406 ms
[10:41:36] Starting 'default'...
[10:41:36] Finished 'default' after 31 ms

hangs indefinitely.............

**Comment by gjungb** [comment]
What do you see when you visit http://localhost:8079 in your browser?

**Comment by dredgerman** [comment]
it will not load that page at all in any browser, a port issue? running apache server on centos with webmin/virtualmin interface

**Comment by dredgerman** [comment]
when searching version, using foundation version, foundation -v or foundation --version or foundation-cli version or any of these variants get

[tom@server myApp]$ foundation version

module.js:340
    throw err;
          ^
Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tom/.nodemodglobal/lib/node_modules/foundation-cli/node_modules/npm/lib/config/core.js:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[tom@server myApp]$

**Comment by dredgerman** [comment]
I give up

**Comment by dredgerman** [comment]
The browser tries to load then times out and says could not load this
page...

**Comment by dredgerman** [comment]
latest attempt to run, checked iptables, port 8079 open, and server listening at this port on localhost but no joy...

> foundation-apps-template@1.1.0 start /home/tom/myApp
> gulp

[14:42:45] Using gulpfile ~/myApp/gulpfile.js
[14:42:45] Starting 'build'...
[14:42:45] Starting 'clean'...
[14:42:45] Finished 'clean' after 22 ms
[14:42:45] Starting 'copy'...
[14:42:45] Starting 'copy:foundation'...
[14:42:46] Finished 'copy:foundation' after 398 ms
[14:42:46] Starting 'sass'...
[14:42:46] Starting 'uglify:foundation'...
[14:42:46] Starting 'uglify:app'...
[14:42:47] Finished 'copy' after 1.44 s
[14:42:47] Finished 'uglify:app' after 205 ms
[14:42:47] Finished 'uglify:foundation' after 628 ms
[14:42:47] Starting 'uglify'...
[14:42:47] Finished 'uglify' after 12 μs
[14:42:47] Finished 'sass' after 1.74 s
[14:42:47] Starting 'copy:templates'...
[14:42:47] Finished 'copy:templates' after 16 ms
[14:42:47] Finished 'build' after 2.2 s
[14:42:47] Starting 'server'...
[14:42:49] Webserver started at http://localhost:8079
[14:42:49] Finished 'server' after 1.23 s
[14:42:49] Starting 'default'...
[14:42:49] Finished 'default' after 22 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)

npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "node" "/home/tom/.nodemodglobal/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE
npm ERR! foundation-apps-template@1.1.0 start: `gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the foundation-apps-template@1.1.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-apps-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-apps-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tom/myApp/npm-debug.log
[tom@server myApp]$

[npm-debug.txt](https://github.com/zurb/foundation-apps/files/43128/npm-debug.txt)

**Comment by dredgerman** [comment]
https://github.com/zurb/foundation-apps/issues/147

See issue from almost exactly one year ago no resolution then either at least not one that helps... Carried out All these steps and no use,  running as su do is not a solution...

**Comment by dredgerman** [comment]
Get started building amazing websites with Foundation. We want to get you up and running as quickly as possible so you can build great things! 

What a joke....

**Comment by blackhoundlabs** [comment]
@dredgerman you are so right!!!
second day with correction of their npm dependencies - as quickly as possible
