### ISSUE TITLE
Installation fails to create bower components

### ISSUE THREAD

**Issue by gorelog** [zurb/foundation-apps#784]
I’ve tried installing on an Ubuntu VM with no success. 

I have tried multiple times using the CLI install directions here : http://foundation.zurb.com/apps/docs/#!/installation as well as these (older ?) directions here: https://github.com/zurb/foundation-apps.

I get the same errors when trying to run “foundation watch”. It is not finding the path to the “helpers/functions” in _settings.scss. I’m also not seeing any bower_components directory in my root. What am I missing?

```

> foundation-apps-template@1.2.0 start /home/vagrant/Code/Laravel/public/rrv2/a
> gulp

[02:35:03] Using gulpfile ~/Code/Laravel/public/rrv2/a/gulpfile.js
[02:35:03] Starting 'build'...
[02:35:03] Starting 'clean'...
[02:35:03] Finished 'clean' after 12 ms
[02:35:03] Starting 'copy'...
[02:35:03] Starting 'copy:foundation'...
[02:35:06] Finished 'copy:foundation' after 3.14 s
[02:35:06] Starting 'sass'...
[02:35:12] Starting 'uglify:foundation'...
[02:35:12] Starting 'uglify:app'...
[02:35:12] Finished 'uglify:foundation' after 68 ms
[02:35:12] Finished 'copy' after 8.87 s
[02:35:12] Finished 'uglify:app' after 97 ms
[02:35:12] Starting 'uglify'...
[02:35:12] Finished 'uglify' after 13 μs

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: client/assets/scss/_settings.scss
Error: File to import not found or unreadable: helpers/functions
       Parent style sheet: /home/vagrant/Code/Laravel/public/rrv2/a/client/assets/scss/_settings.scss
        on line 32 of client/assets/scss/_settings.scss
>> @import "helpers/functions";
   ^

    at options.error (/home/vagrant/Code/Laravel/public/rrv2/a/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:277:32)
Error: foundation-apps-template@1.2.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (/usr/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:24:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
![screen shot 2016-03-09 at 9 08 46 pm](https://cloud.githubusercontent.com/assets/895909/13658276/29a38b30-e63b-11e5-8d72-f515b0a62dec.png)

```
And here is a log (http://pastebin.com/P0FdEAXD) of the installation. Please let me know if there is anything else that I could provide that would be helpful.

Thank you.

**Comment by gorelog** [comment]
Running `bower install` revealed permission issues with /home/vagrant/.local/share/bower.

`Error: EACCES: permission denied, mkdir '/home/vagrant/.local/share/bower/empty'`

Creating the following directories: /home/vagrant/.local/share/bower and /home/vagrant/.local/share/bower/empty and then running `bower install --allow-root` fixed me up.
