### ISSUE TITLE
The app doc page is broken

### ISSUE THREAD

**Issue by wicktus** [zurb/foundation-apps#828]
Hello,
It's impossible to see the html templates in the doc section for foundation apps 
the following error is shown in the console : 

`app.js:4 TypeError: Cannot read property 'configure' of undefined
    at Object.$get (http://foundation.zurb.com/apps/docs/assets/js/app.js:34:699)
    at Object.invoke (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:2367)
    at http://foundation.zurb.com/apps/docs/assets/js/app.js:4:3609
    at getService (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:1736)
    at Object.invoke (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:2299)
    at extend.instance (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:50681)
    at nodeLinkFn (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:27155)
    at compositeLinkFn (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:18385)
    at compositeLinkFn (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:18475)
    at compositeLinkFn (http://foundation.zurb.com/apps/docs/assets/js/app.js:4:18475) <div ng-class="['ui-animation']" ui-view="" autoscroll="" class="ng-scope" data-ng-animate="1">`

thanks :)

**Comment by JonathenYgrene** [comment]
Yeah Hella broke!

**Comment by soumak77** [comment]
ZURB has unofficially dropped support for this framework and it is now being maintained by the community.  The docs can be found here: https://base-apps.github.io/angular-base-apps

**Comment by Seb-** [comment]
@soumak77  Thanks for the link and the heads up. Is it the best (production ready) fork available? I'm currently reading the "why" issue but this is rather long.

**Comment by wicktus** [comment]
Myabe they have other priorities (new framework...) or maybe they're developing it for angularjs v2 who knows...thing is they didn't explicitely state that they indeed abandoned but it's clear that they're not working at all on it. Let's see but this lack of communication is unhealthy for Zurb's reputation, you can deprecate this framework but say it at least ;).

**Comment by Opticsponge** [comment]
I did hear from Zurb last march when I emailed them about angular 2 support. They responded with this [link]( https://zurb.createsend.com/campaigns/reports/viewCampaign.aspx?d=y&c=D1DB5D1EACAC32B4&ID=D0031E1D4F9F755C&temp=False&tx=0) and mentioned a rough timeline for later this year. That was months ago, would be nice to get update.

**Comment by wicktus** [comment]
There you go...I think they're hard at work on too many things, foundation for app might not be the top 1 priority but again even angular-material is now in maintenance mode because they're developing the angularjs 2 version so I won't judge zurb too fast. I'm pretty sure they will release a new foundation app version in the future.

**Comment by soumak77** [comment]
@Seb- Yes the fork is production ready.  I use it for all apps in my company.  I have even have them running the v2.0 prerelease without issues.

**Comment by wicktus** [comment]
The page is fixed now ;). Also foundation app is apparently going to be replaced by a foundation site framework that will support angular, react and vanilla js...hence the silence around foundation app. It's not really abandonned it's just going to be replaced by a more complete unified foundation site framework.
