### ISSUE TITLE
Problem Installing Foundation on windows 

### ISSUE THREAD

**Issue by successdavis** [zurb/foundation-apps#836]
I have spent 3 days trying to install foundation and its only getting worst at first the installation went well, I only get stuck when I run Foundation new and I get this error

There were some problems during the installation.
✓ New project folder created.
✗ Node modules not installed. Try running npm install manually.
✓ Bower components installed.

after googling I came across this article 
https://foundation.zurb.com/forum/posts/55733-finally-a-no-error-install-on-windows-10#
which i followed vividly and it only made things worst for me and now I get this new error

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\STECHMAX\AppData\Roaming\npm\node_modules\fo
undation-cli\bin\foundation.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

I did a system restore so as to start all over
I re-install node v10.8.0-x64.msi, 

I still get same error

Please help me out. I am really stock

**Comment by soumak77** [comment]
@successdavis this repo is deprecated, try using https://github.com/base-apps/angular-base-apps instead
